[project]
name = "iapyc"
version = "0.1.0"
description = "Yet another IaC tool"
authors = [
    {name = "CYTMWIA"},
]
dependencies = [
    "fabric",
    "jinja2",
    "pyyaml",
    "ansible-core",
    "colorama",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}
